### ISSUE TITLE
创建表的时间添加配置全局索引报错

### ISSUE THREAD

**Issue by bangquanwu** [aliyun/aliyun-tablestore-nodejs-sdk#26]
**err : { 403:
OTSOperationForbidden4You are forbidden to do this operation: CreateTable.
    at Request.extractError (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\client.js:92:44)
    at Request.callListeners (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\sequential_executor.js:113:20)
    at Request.emit (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\sequential_executor.js:81:10)
    at Request.emit (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\request.js:189:14)
    at Request.transition (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\request.js:57:10)
    at AcceptorStateMachine.runTo (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\request.js:24:12)
    at E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\request.js:36:10
    at Request.<anonymous> (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\request.js:73:9)
    at Request.<anonymous> (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\request.js:191:12)
    at Request.callListeners (E:\pro\nc-draw\node_modules\_tablestore@4.3.2@tablestore\lib\sequential_executor.js:90:20)**

### createTable参数:
`{
    tableMeta: {
      tableName: name,
      primaryKey: pks,
      definedColumn: dcs
    },
    reservedThroughput: {
      capacityUnit: {
        read: 0,
        write: 0
      }
    },
    tableOptions: {
      timeToLive: -1,// 数据的过期时间, 单位秒, -1代表永不过期. 假如设置过期时间为一年, 即为 365 * 24 * 3600.
      maxVersions: 1// 保存的最大版本数, 设置为1即代表每列上最多保存一个版本(保存最新的版本).
    },
    streamSpecification: {
      enableStream: false, //globalIndex不支持开启Stream
    },
    indexMetas: [
      {
        name: 'indexaa',
        primaryKey: ['$username'],
        definedColumn: ['password']
      },
      // {
      //   name: 'index',
      //   primaryKey: pks.map(p=>p.name),
      //   definedColumn: dcs.map(p=>p.name)
      // }
    ]
  }`

**实现目标是创建表格的同时生成全局索引**  
**权限是管理员权限，可以操作阿里云所有资源，参数去掉indexMetas属性可以正常创建表格**

**Comment by bangquanwu** [comment]
@cf @boxiaowpl @wangtantan 各位老师能不能帮忙看下问题

**Comment by Dehuali** [comment]
我也是索引出问题，这么久都没有人管。。。

**Comment by wangtantan** [comment]
您好，这个问题是由于你们有开通二级索引造成的，二级索引是实例级别开通的，目前尚未对所有实例默认开启。请加入公开交流群，联系技术支持同学开通
交流群1：11789671
交流群2：23307953
